DWAPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.0
  max_vel_theta: 1.2
  min_vel_theta: 0.4
  acc_lim_x: 2.5
  acc_lim_theta: 3.2

  sim_time: 1.0
  sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 40
  controller_frequency: 10.0

  path_distance_bias: 64.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05
  prune_plan: true
  prefer_forward: true
