global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0  # 🔴 Increase to ensure updates
  publish_frequency: 2.0
  transform_tolerance: 0.5
  rolling_window: false
  track_unknown_space: true

  static_map: false  # 🔴 MUST be false for dynamic maps
  map_topic: /rtabmap/grid_map  # 🔴 Ensure this matches RTAB-Map output
  always_send_full_costmap: true  # 🔴 Forces updates

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  map_topic: "/rtabmap/grid_map"   # Use RTAB-Map's 2D map
  subscribe_to_updates: true
  track_unknown_space: true
  lethal_cost_threshold: 80  # Ensure obstacles are properly detected

obstacle_layer:
  enabled: true
  max_obstacle_height: 1.0
  min_obstacle_height: 0.1
  observation_sources: point_cloud_sensor
  point_cloud_sensor:
    data_type: PointCloud2
    topic: /rtabmap/cloud_obstacles
    marking: true
    clearing: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    min_obstacle_height: 0.2
    max_obstacle_height: 1.0
    filter_size: 0.2  # Increase to remove small noise

inflation_layer:
  enabled: true
  inflation_radius: 0.9
  cost_scaling_factor: 10.0