local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: cloud
    cloud: {
      data_type: PointCloud2,
      topic: /rtabmap/cloud_obstacles,
      marking: true,
      clearing: true,
      min_obstacle_height: 0.0,
      max_obstacle_height: 2.5
    }

  inflation_layer:
    inflation_radius: 0.5
