TebLocalPlannerROS:
  max_vel_x: 0.8  # Increase if your robot is too slow
  max_vel_x_backwards: 0.2  # Prevent high-speed reversals
  max_vel_theta: 0.6  # Increase for sharper turns
  acc_lim_x: 0.8  # Adjust acceleration limits
  acc_lim_theta: 0.6
  viapoints_all_candidates: true

  # If your robot keeps stopping, reduce this!
  inflation_dist: 0.4  # Reduce if the robot hesitates too much

  # Increase robot agility
  max_global_plan_lookahead_dist: 2.5
  global_plan_overwrite_orientation: true
  allow_init_with_backwards_motion: true
  control_frequency: 10.0  # Default is 5 Hz, increase if needed
  xy_goal_tolerance: 0.05  # Adjust this to match your system (default: 0.2)
  yaw_goal_tolerance: 0.05  # Ensure the robot reaches the correct orientation
  free_goal_vel: false  # Force the robot to stop when reaching the goal
  min_obstacle_dist: 0.5  # Increase this to make paths more spaced out
  global_plan_viapoint_sep: 0.01  # Increase this to space out waypoints
  dt_ref: 0.5  # Default is 0.3, try increasing it
  weight_viapoint: 0.5  # Default is 1.0
  weight_kinematics_forward_drive: 5.0  # Prioritize forward motion
  weight_kinematics_turning_radius: 1.0 # Avoid sharp turns
  feasibility_check_no_poses: 20        # Reduce rapid re-planning
  weight_shortest_path: 3.0              # Default: 0.0 (new in Noetic)
  
  min_turning_radius: 0.0  # For differential drive
  
  odom_topic: odom
  include_viapoints: true
  
  